version: '3.7'
services:
  database:
    image: postgres:15
    container_name: postgres
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432

  redis:
    image: redis:7
    container_name: redis
    ports:
      - 6379:6379

  myscore:
    image: myscore:1.2
    container_name: myscore_app
    build:
      context: .
    env_file:
      - .env-non-dev
    command: ['docker/app.sh']
    ports:
      - 80:80
    depends_on:
      - database
      - redis

  celery:
    image: celery
    build:
      context: .
    container_name: celery
    env_file:
      - .env-non-dev
    command: ['docker/celery.sh', 'celery']
    depends_on:
      - redis

  flower:
    image: flower
    build:
      context: .
    container_name: flower
    env_file:
      - .env-non-dev
    command: [ 'docker/celery.sh', 'flower' ]
    depends_on:
      - redis
