"""Create table coaches

Revision ID: 2d61d0a7e7e1
Revises: b7e0584de0c0
Create Date: 2023-11-09 23:59:53.142888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d61d0a7e7e1'
down_revision: Union[str, None] = 'b7e0584de0c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coaches',
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('second_name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('country_birth', sa.String(), nullable=False),
    sa.Column('current_club', sa.String(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('clubs', sa.Column('coach_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'clubs', 'coaches', ['coach_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clubs', type_='foreignkey')
    op.drop_column('clubs', 'coach_id')
    op.drop_table('coaches')
    # ### end Alembic commands ###
