"""Create table clubs

Revision ID: b7e0584de0c0
Revises: 
Create Date: 2023-11-09 23:21:51.134528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7e0584de0c0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date_of_foundation', sa.Date(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('players_quantity', sa.Integer(), nullable=False),
    sa.Column('stuff_quantity', sa.Integer(), nullable=False),
    sa.Column('coach_name', sa.String(), nullable=False),
    sa.Column('league_name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clubs')
    # ### end Alembic commands ###
