"""Update table refreshtokens

Revision ID: 3bf3d499fcd6
Revises: 8c415ae1bf93
Create Date: 2023-11-13 21:35:14.768664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bf3d499fcd6'
down_revision: Union[str, None] = '8c415ae1bf93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('clubs_player_id_fkey', 'clubs', type_='foreignkey')
    op.drop_column('clubs', 'player_id')
    op.drop_constraint('leagues_club_id_fkey', 'leagues', type_='foreignkey')
    op.drop_column('leagues', 'club_id')
    op.add_column('refreshtokens', sa.Column('expire_at', sa.Integer(), nullable=False))
    op.add_column('refreshtokens', sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refreshtokens', 'created_at')
    op.drop_column('refreshtokens', 'expire_at')
    op.add_column('leagues', sa.Column('club_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('leagues_club_id_fkey', 'leagues', 'clubs', ['club_id'], ['id'])
    op.add_column('clubs', sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('clubs_player_id_fkey', 'clubs', 'players', ['player_id'], ['id'])
    # ### end Alembic commands ###
