"""Optional coach_id in clubs table

Revision ID: 2504ec1f8d6b
Revises: 49941d5604af
Create Date: 2023-11-22 21:00:38.218028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2504ec1f8d6b'
down_revision: Union[str, None] = '49941d5604af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
