"""Create table leagues

Revision ID: f55f265629bc
Revises: 2d61d0a7e7e1
Create Date: 2023-11-10 00:07:35.430195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f55f265629bc'
down_revision: Union[str, None] = '2d61d0a7e7e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('league_name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('clubs_number', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('clubs', sa.Column('league_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'clubs', 'leagues', ['league_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clubs', type_='foreignkey')
    op.drop_column('clubs', 'league_id')
    op.drop_table('leagues')
    # ### end Alembic commands ###
