"""Added rating for clubs and players

Revision ID: 51ec8d2e2f66
Revises: 7ebcb2c7f736
Create Date: 2024-01-04 01:33:45.652650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51ec8d2e2f66'
down_revision: Union[str, None] = '7ebcb2c7f736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('rating', sa.Integer(), nullable=False))
    op.add_column('players', sa.Column('rating', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'rating')
    op.drop_column('clubs', 'rating')
    # ### end Alembic commands ###
