"""Deleted clum_id in coaches table

Revision ID: 7bff5434b1de
Revises: 51ec8d2e2f66
Create Date: 2024-01-04 02:17:19.546742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bff5434b1de'
down_revision: Union[str, None] = '51ec8d2e2f66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('coaches_club_id_fkey', 'coaches', type_='foreignkey')
    op.drop_column('coaches', 'club_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coaches', sa.Column('club_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('coaches_club_id_fkey', 'coaches', 'clubs', ['club_id'], ['id'])
    # ### end Alembic commands ###
